"""UnitApe: static Python unittest skeleton generation.

The analyzed source is parsed with ``ast`` only; UnitApe never imports or executes
it while generating skeletons.
"""

from __future__ import annotations

import argparse
import ast
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class GeneratedTest:
    source: Path
    class_name: str
    output: Path


def iter_python_files(source: Path) -> Iterable[Path]:
    """Yield Python source files in deterministic order."""
    source = source.expanduser().resolve()
    if source.is_file():
        if source.suffix != ".py":
            raise ValueError(f"Source file must end in .py: {source}")
        yield source
        return
    if not source.is_dir():
        raise FileNotFoundError(f"Source path does not exist: {source}")

    for path in sorted(source.rglob("*.py")):
        if path.is_file():
            yield path


def parse_classes(source_file: Path) -> list[ast.ClassDef]:
    """Parse top-level classes without importing or executing the source."""
    try:
        source_text = source_file.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        source_text = source_file.read_text(encoding="utf-8", errors="replace")

    try:
        tree = ast.parse(source_text, filename=str(source_file))
    except SyntaxError as exc:
        raise SyntaxError(f"Cannot parse {source_file}: {exc}") from exc

    return [node for node in tree.body if isinstance(node, ast.ClassDef)]


def public_methods(class_node: ast.ClassDef) -> list[str]:
    """Return deterministic public method names declared directly on a class."""
    names = {
        node.name
        for node in class_node.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and not node.name.startswith("_")
    }
    return sorted(names)


def _slug(value: str) -> str:
    slug = re.sub(r"[^0-9A-Za-z_]+", "_", value).strip("_").lower()
    return slug or "generated"


def render_test_skeleton(source_file: Path, class_node: ast.ClassDef) -> str:
    """Render a syntactically valid, explicitly skipped unittest skeleton.

    The generator intentionally does not emit unconditional ``assertTrue(True)``
    placeholders because those create false-positive test suites.
    """
    methods = public_methods(class_node)
    lines = [
        '"""Generated by UnitApe. Review and replace every skipped placeholder."""',
        "",
        "import unittest",
        "",
        f"# Source: {source_file.name}",
        f"# TODO: import {class_node.name} from the project under test.",
        "",
        f"class Test{class_node.name}(unittest.TestCase):",
    ]

    if not methods:
        lines.extend(
            [
                '    @unittest.skip("TODO: add a behavior-focused test")',
                "    def test_placeholder(self) -> None:",
                '        self.fail("replace generated placeholder")',
            ]
        )
    else:
        for method in methods:
            lines.extend(
                [
                    "",
                    f'    @unittest.skip("TODO: define expected behavior for {method}")',
                    f"    def test_{_slug(method)}(self) -> None:",
                    '        self.fail("replace generated placeholder")',
                ]
            )

    lines.extend(["", "", 'if __name__ == "__main__":', "    unittest.main()", ""])
    return "\n".join(lines)


def generate_tests(source: str | Path, output: str | Path, *, overwrite: bool = False) -> list[GeneratedTest]:
    """Generate unittest skeleton files for top-level classes."""
    source_path = Path(source).expanduser().resolve()
    output_path = Path(output).expanduser().resolve()
    output_path.mkdir(parents=True, exist_ok=True)

    if not output_path.is_dir():
        raise ValueError(f"Output path is not a directory: {output_path}")

    generated: list[GeneratedTest] = []
    for source_file in iter_python_files(source_path):
        for class_node in parse_classes(source_file):
            filename = f"test_{_slug(source_file.stem)}_{_slug(class_node.name)}.py"
            destination = output_path / filename
            if destination.exists() and not overwrite:
                raise FileExistsError(f"Refusing to overwrite existing file: {destination}")
            destination.write_text(
                render_test_skeleton(source_file, class_node),
                encoding="utf-8",
                newline="\n",
            )
            generated.append(GeneratedTest(source_file, class_node.name, destination))

    return generated


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate explicit unittest skeletons from Python classes without executing source code."
    )
    parser.add_argument("source", help="Python file or directory to inspect")
    parser.add_argument("output", help="Directory in which generated tests are written")
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="replace an existing generated test file instead of failing closed",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        generated = generate_tests(args.source, args.output, overwrite=args.overwrite)
    except (FileExistsError, FileNotFoundError, SyntaxError, ValueError) as exc:
        print(f"UnitApe error: {exc}")
        return 2

    if not generated:
        print("No top-level classes found; no files generated.")
        return 0

    for item in generated:
        print(f"Generated {item.output} from {item.source.name}:{item.class_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
